worker_processes auto;

events { worker_connections 4096; }

http {
  proxy_cache_path /var/cache/nginx/flags keys_zone=flags:16m max_size=1g inactive=5s use_temp_path=off;
  upstream feature_flag_api { server app:8080; keepalive 128; }
  server {
    listen 80;
    location / {
      proxy_pass http://feature_flag_api;
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }
    location ~ ^/v1/evaluate/ {
      proxy_pass http://feature_flag_api;
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      proxy_set_header Connection "";
      proxy_set_header Accept-Encoding gzip;
      proxy_cache flags;
      proxy_cache_methods GET HEAD;
      proxy_cache_key "$scheme$proxy_host$request_uri|$http_accept_encoding";
      proxy_cache_valid 200 1s;
      proxy_cache_valid 204 1s;
      proxy_cache_lock on;
      proxy_cache_background_update on;
      proxy_cache_use_stale error timeout updating http_500 http_502 http_503 http_504;
      proxy_ignore_headers Cache-Control;
      add_header X-Edge-Cache $upstream_cache_status always;
    }
    location /test/large-payload {
      proxy_pass http://feature_flag_api;
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      proxy_set_header Connection "";
      proxy_set_header Accept-Encoding gzip;
      proxy_cache flags;
      proxy_cache_methods GET HEAD;
      proxy_cache_key "$scheme$proxy_host$request_uri|$http_accept_encoding";
      proxy_cache_valid 200 5s;
      proxy_cache_lock on;
      proxy_cache_background_update on;
      proxy_cache_use_stale error timeout updating http_500 http_502 http_503 http_504;
      proxy_ignore_headers Cache-Control;
      add_header X-Edge-Cache $upstream_cache_status always;
    }
  }
}